### ISSUE TITLE
Manage Groups

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-rbac#22]
## Context

Allow the declaration of Groups.

For example:

```yaml
rbac:
  groups:
    some-group:
      users:
        - some-user1
        - some-user2
        - some-user3
```

## Alternatives
Static manifests
